import React from 'react';
import fs from 'fs';
import path from 'path';
import { createRoot } from 'react-dom/client';
import { act } from 'react-dom/test-utils';
import { LectureCard800 } from './LectureCard800';
import { writeForgotten800 } from './lecture800-storage';
import { lectureLearningPreviews804, lectureRepeatAt804, applyLectureDue804 } from './lectureLearning804';
jest.mock('./pdf791-engine', () => ({ loadPdfEngine791: jest.fn() }));
jest.mock('./lecture800-storage', () => ({ readForgotten800: async () => ({}), writeForgotten800: jest.fn(async () => []), readLectureMedia800: jest.fn() }));
const source = fs.readFileSync(path.join(__dirname, 'App.js'), 'utf8');
const scriptPackage = require.resolve('react-scripts/package.json');
const babel = require(require.resolve('@babel/core', { paths: [scriptPackage] }));
const jsx = require.resolve('@babel/plugin-transform-react-jsx', { paths: [scriptPackage] });
const begin = source.indexOf('function SM2AnswerFooter('), end = source.indexOf('\nfunction getFullQuestionBank(', begin);
const { code } = babel.transformSync(source.slice(begin, end), { plugins: [jsx], babelrc: false, configFile: false });
const apply = jest.fn(async (_card, rating) => ({ rating }));
const deps = { React, useState: React.useState, useEffect: React.useEffect, useRef: React.useRef, STORAGE: {}, SM2_RATING: { AGAIN: 1, HARD: 2, GOOD: 3, EASY: 4 }, SM2_RATING_ORDER: ['Igen', 'Svær', 'God', 'Nem'].map((label, i) => ({ key: i + 1, label, shortcut: String(i + 1), hint: '' })), fsrsPreviewOfficial: async () => ({ 3: { delayMs: 86400000, newIntervalDays: 1 }, 4: { delayMs: 172800000, newIntervalDays: 2 } }), fsrsApplyOfficial: apply, flashcardReviewEventId: () => 'event', sm2FormatIntervalDa: ms => String(ms), lectureLearningPreviews804, lectureRepeatAt804, applyLectureDue804 };
const Footer = new Function(...Object.keys(deps), `${code}\nreturn SM2AnswerFooter;`)(...Object.values(deps));
const reviewerStart = source.indexOf('function FlashcardReviewer71('), reviewerEnd = source.indexOf('\nfunction MCQ(', reviewerStart);
const reviewerCode = babel.transformSync(source.slice(reviewerStart, reviewerEnd), { plugins: [jsx], babelrc: false, configFile: false }).code;
const reviewerDeps = { React, useState: React.useState, LectureCard800, FsrsRatingControls: Footer, Flashcard71Styles: () => null, Icon: () => null, translate: value => value?.da || value || '' };
const Reviewer = new Function(...Object.keys(reviewerDeps), `${reviewerCode}\nreturn FlashcardReviewer71;`)(...Object.values(reviewerDeps));
global.IS_REACT_ACT_ENVIRONMENT = true;
let host, root;
beforeEach(() => { apply.mockImplementation(async (_card, rating, id, now) => ({ id, dueDate: new Date(now + 86400000).toISOString(), fsrs: { card: { due: new Date(now + 86400000).toISOString(), stability: 1, difficulty: 5, state: 2 }, reviews: [{ rating }] } })); host = document.createElement('div'); document.body.appendChild(host); root = createRoot(host); });
afterEach(() => { act(() => root.unmount()); host.remove(); });
test('forgotten answers expose only Again/Hard and cannot bypass the restriction by keyboard', async () => {
  await act(async () => root.render(<Footer questionId="c" spacedData={{}} setSpacedData={() => {}} onRated={() => {}} maxRating={2} />));
  expect([...host.querySelectorAll('[data-rating]')].map(el => el.dataset.rating)).toEqual(['1', '2']);
  for (const key of ['3', '4', 'Enter', ' ']) await act(async () => window.dispatchEvent(new KeyboardEvent('keydown', { key, bubbles: true, cancelable: true })));
  expect(apply).not.toHaveBeenCalled();
  await act(async () => window.dispatchEvent(new KeyboardEvent('keydown', { key: '2', bubbles: true })));
  expect(apply).toHaveBeenCalledWith(null, 2, 'c', expect.any(Number));
});
test('ordinary cards still offer all four ratings and the Good keyboard shortcut', async () => {
  await act(async () => root.render(<Footer questionId="c" spacedData={{}} setSpacedData={() => {}} onRated={() => {}} />));
  expect(host.querySelectorAll('[data-rating]')).toHaveLength(4);
  await act(async () => window.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true })));
  expect(apply).toHaveBeenCalledWith(null, 3, 'c', expect.any(Number));
});
test('the real reviewer restricts ratings immediately when a forgotten checkbox is saved and restores them when cleared', async () => {
  let save;
  writeForgotten800.mockImplementationOnce(() => new Promise(resolve => { save = resolve; }));
  const question = { id: 'list', lectureContent: { section: { title: 'Grundlag' }, glossary: [], sources: [], card: { type: 'recall-list', question: 'Hvad er vigtigt?', answerItems: [{ id: 'a', text: 'Første svarpunkt' }], sourceRefs: [] } } };
  await act(async () => root.render(<Reviewer question={question} lectureScope800="test" revealed spacedData={{}} setSpacedData={() => {}} onRated={() => {}} />));
  expect(host.querySelectorAll('[data-rating]')).toHaveLength(4);
  act(() => host.querySelector('input').click());
  expect(host.querySelectorAll('[data-rating]')).toHaveLength(2);
  await act(async () => save(['a']));
  expect(host.querySelectorAll('[data-rating]')).toHaveLength(2);
  await act(async () => host.querySelector('input').click());
  expect(host.querySelectorAll('[data-rating]')).toHaveLength(4);
});
test('the guided ten-minute button forwards its actual retry deadline after an Again/Hard reset', async () => {
  const onRated = jest.fn();
  await act(async () => root.render(<Footer questionId="c" spacedData={{}} setSpacedData={() => {}} onRated={onRated} sectionPractice practiceReset804 />));
  expect(host.querySelector('[data-rating="3"] .fsrs-rating-interval').textContent).toBe('600000');
  const before = Date.now();
  await act(async () => host.querySelector('[data-rating="3"]').click());
  const metadata = onRated.mock.calls[0][2];
  expect(metadata.repeatAt804).toBeGreaterThanOrEqual(before + 600000);
  expect(metadata.repeatAt804).toBe(metadata.reviewedAt + 600000);
});
